#footprint: [[-0.1, -0.25], [-0.1, 0.25], [0.5, 0.25], [0.5, -0.25]]
footprint: [[-0.7, -0.25], [-0.7, 0.25], [0.14, 0.25], [0.14, -0.25]]
footprint_padding: 0.2   #Earlier it was 0.05

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 20.0 #The "obstacle_range" parameter determines the maximum range sensor reading that will result in an obstacle being put into the costmap
raytrace_range: 10.0 #The "raytrace_range" parameter determines the range to which we will raytrace freespace given a sensor reading. 

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, clearing: true, marking: true, topic: /zed/scan, inf_is_valid: true}
    #laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /zed/scan, marking: true, clearing: false}
inflation:
    inflation_radius: 0.3 #was 0.5 0.3
  
plugins:
  - {name: custom_lane_layer, type: "custom_costmap_layer::LaneCostmapLayer"}


